<?php

/** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\BaseAdminTemplate */

/** @var \Algolia\AlgoliaSearch\ViewModel\Adminhtml\Common $viewModel */
$viewModel = $this->getViewModel();

$applicationId = $viewModel->getApplicationId();

$isClickAnalyticsEnabled = true;
$isQueryRulesEnabled = true;

$section = $this->getRequest()->getParam('section');

if ($section === 'algoliasearch_cc_analytics') {
    $isClickAnalyticsEnabled = $viewModel->isClickAnalyticsEnabled();
}

if ($section === 'algoliasearch_instant') {
    $isQueryRulesEnabled = $viewModel->isQueryRulesEnabled();
}

$indexingQueueInfoUrl = $this->getUrl('algolia_algoliasearch/queue/info');
$indexingQueueConfigUrl = $this->getUrl('adminhtml/system_config/edit/section/algoliasearch_queue');
$indexingQueuePageUrl = $this->getUrl('algolia_algoliasearch/queue/index');

$ajaxCheckUrl = $this->getUrl('algolia_algoliasearch/landingpage/checkUrl');
$ajaxCheckQuery = $this->getUrl('algolia_algoliasearch/query/checkQuery');

$icons = [
    'iconDocs' => $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-docs.svg'),
    'iconFaq' => $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-faq.svg'),
    'iconIssues' => $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-issues.svg'),
];

$videoConfig = $viewModel->getVideoConfig($section);
$linksConfig = $viewModel->getLinksConfig($section);

?>

<script>
var applicationId = <?php echo json_encode($applicationId); ?>;
var isClickAnalyticsEnabled = <?php echo json_encode($isClickAnalyticsEnabled); ?>;
var isQueryRulesEnabled = <?php echo json_encode($isQueryRulesEnabled); ?>;
var indexingQueueConfigUrl = <?php echo json_encode($indexingQueueConfigUrl); ?>;
var indexingQueuePageUrl = <?php echo json_encode($indexingQueuePageUrl); ?>;
var indexingQueueInfoUrl = <?php echo json_encode($indexingQueueInfoUrl); ?>;
var ajaxCheckUrl = <?php echo json_encode($ajaxCheckUrl); ?>;
var ajaxCheckQuery = <?php echo json_encode($ajaxCheckQuery); ?>;
var icons = <?php echo json_encode($icons); ?>;
var videoConfig = <?php echo json_encode($videoConfig); ?>;
var linksConfig = <?php echo json_encode($linksConfig); ?>;

document.addEventListener("DOMContentLoaded", function(event) {
	requirejs(['algoliaAdminBundle'], function(algoliaAdminBundle) {
		algoliaAdminBundle.$(function ($) {
			$('form[action*="algoliasearch"] .accordion .config .label').css('width', 'auto');
			$('form[action*="algoliasearch"] .accordion .config .value').css('width', 'auto');

			var fixHelper = function(e, ui) {
				ui.children().each(function() {
					$(this).width($(this).width());
				});

				return ui;
			};

			setTimeout(function () {
				$('form[action*="algoliasearch"] .admin__control-table tbody').sortable({
					containment: "parent",
					items: 'tr',
					tolerance: 'pointer',
					helper: fixHelper,
					start: function (event, ui) {
						$(ui.item).css('margin-left', '10px');
					}
				});

				$('form[action*="algoliasearch"] .admin__control-table tbody tr td').css('cursor', 'move');
			}, 1000);

			/** FEATURE ENABLEMENT **/
			var notEnabledText = `
				<br>
				<div class="algolia_block icon-stars">
					To get access to this Algolia feature,
					please consider <a href="https://www.algolia.com/billing/overview" target="_blank">upgrading to a higher plan</a>.
				</div>
			`;

			// Click analytics
			if (isClickAnalyticsEnabled === false) {
				$('#algoliasearch_cc_analytics_cc_analytics_group table').hide();
				$('#algoliasearch_cc_analytics_cc_analytics_group .comment').after(notEnabledText);
			}

			// Query rules in facets
			if (isQueryRulesEnabled === false) {
				var notEnabledText = `
					<br>
					<div class="algolia_block icon-stars">
						To be able to create Query rules for facets,
						please consider <a href="https://www.algolia.com/billing/overview" target="_blank">upgrading to a higher plan</a>.
					</div>
				`;

				$('select[name*=create_rule]').val('2').prop('disabled', 'disabled');
				$('#row_algoliasearch_instant_instant_facets .algolia_block.blue').after(notEnabledText);
			}

			// QUEUE INFO

			var url = window.location.href;
			if (url.indexOf('section/algoliasearch_') !== -1) {
				$.getJSON(indexingQueueInfoUrl, function(queueInfo) {
					var message = `
						<div class="algolia_block icon-warning">
							<div class="heading"><a href="` + indexingQueueConfigUrl + `">Indexing Queue</a> is not enabled</div>
							It is highly recommended that you enable it, especially if you are on a production environment.
							<br><br>
							Find out more about Indexing Queue in <a href="https://www.algolia.com/doc/integration/magento-2/how-it-works/indexing-queue/?utm_source=magento&utm_medium=extension&utm_campaign=magento_2&utm_term=shop-owner&utm_content=doc-link" target="_blank">documentation</a>.
						</div>`;

					if (queueInfo.isEnabled === true) {
						message = `
							<div class="algolia_block icon-bulb">
								<div class="heading">Queued indexing jobs</div>
								Number of queued jobs: <strong>` + queueInfo.currentSize + `</strong>.
								Assuming your queue runner runs every 5 minutes, all jobs will be processed
								in approx. ` + queueInfo.eta + `.
								You may want to <a href="` + indexingQueuePageUrl + `">clear the queue</a> or <a href="` + indexingQueueConfigUrl + `">configure indexing queue</a>.
								<br><br>
								Find out more about Indexing Queue in <a href="https://www.algolia.com/doc/integration/magento-2/how-it-works/indexing-queue/?utm_source=magento&utm_medium=extension&utm_campaign=magento_2&utm_term=shop-owner&utm_content=doc-link" target="_blank">documentation</a>.
							</div>`;
					}

					$('.entry-edit').before(message);
				});

				// Admin videos
                var videoTemplate = '';
                // Admin links
                var linksTemplate = '';

                if (videoConfig) {
                    videoTemplate = `
                        <div class="algolia-admin-content-videos">
                            <p>
                                <span>Related video:</span>
                                <a target="_blank" href="` + videoConfig.url + `"><img src="` + videoConfig.thumbnail + `"/></a>
                                <a target="_blank" href="` + videoConfig.url + `">` + videoConfig.title + `</a>
                            </p>
                        </div>`;
                }

                if (linksConfig) {
                    var links = '';
                    for (var i=0; i<linksConfig.length; i++) {
                        links += `<span><img src="` + icons[linksConfig[i].icon] + `"/><a target="_blank" href="` + linksConfig[i].url + `">` + linksConfig[i].title + `</a></span>`;
                        if (i%2 == 1) {
                            links += `<br/>`;
                        }
                    }
                    linksTemplate = `<div class="algolia-admin-content-links"><p>` + links + `</p></div>`;
                }

                var linksAndVideoTemplate = `
                    <div class="algolia-admin-content-wrapper">
                        ` + linksTemplate +  videoTemplate +
                    `</div>
                    <br>
                    <hr>
                    <br>`;
                $('.algolia-admin-content').html(linksAndVideoTemplate);
			}


			// SYNONYMS

			handleSynonyms($('#algoliasearch_synonyms_synonyms_group_enable_synonyms').val());

			$(document).on('change', '#algoliasearch_synonyms_synonyms_group_enable_synonyms', function() {
				handleSynonyms($(this).val());
			});

			function handleSynonyms(enabled) {
				var $rows = $('#row_algoliasearch_synonyms_synonyms_group_synonyms, #row_algoliasearch_synonyms_synonyms_group_oneway_synonyms, #row_algoliasearch_synonyms_synonyms_group_synonyms_file');

				if (enabled === '1') {
					$rows.show();
				} else {
					$rows.hide();
				}
			}

			// ORDERED / UNORDERED
			var $attributesRows = $('#algoliasearch_products_products_product_additional_attributes, #algoliasearch_categories_categories_category_additional_attributes');
			initAttributes($attributesRows);

			$attributesRows.on('click', 'button[id^="addToEndBtn"]', function (e) {
				initAttributes($attributesRows);
			});

			$attributesRows.on('change', 'select[name$="[searchable]"]', function (e) {
				handleAttributes($(this));
			});

			function initAttributes($attributesRows) {
				$attributesRows.find('select[name$="[searchable]"]').each(function(e) {
					handleAttributes($(this));
				});
			}

			function handleAttributes($selectBox) {
				var selectValue = $selectBox.val(),
					$input = $selectBox.parent('td').next().find('select[name$="[order]"]');

				if(selectValue !== '1') {
					$input.hide();
				}
				else {
					$input.show();
				}
			}

			// EVENTS TRACKING
			function trackEvent(eventName, data) {
				if (!navigator.sendBeacon) {
					return;
				}

				data = data || {};

				const postData = JSON.stringify({
					appId: applicationId,
					eventName: eventName,
					data: data
				});

				navigator.sendBeacon('https://magento-proxy.algolia.com/event/', postData);
			}

			var eventsToTrack = [
                {
	                // Click on Analytics Overview in main menu
                    selector: 'li[data-ui-id="menu-algolia-algoliasearch-analytics"] a',
                    name: 'magento2.menu',
                    data: {
                        'name': 'Clicked Analytics'
                    }
                },
				{
					// Update dates on analytics overview page
					selector: '#algolia-analytics-form button.algolia-daterange-submit',
					name: 'magento2.analytics',
					data: {
						'name': 'Updated the Dates'
					}
				},
				{
					// Click on "See more popular searches"
					selector: '.popular-searches .analytics-footer a',
					name: 'magento2.analytics',
					data: {
						'name': 'Clicked for More Data'
					}
				},
				{
					// Click on "See more popular results"
					selector: '.popular-results .analytics-footer a',
					name: 'magento2.analytics',
					data: {
						'name': 'Clicked for More Results'
					}
				},
				{
					// Click on "See more no results searches"
					selector: '.no-result-searches .analytics-footer a',
					name: 'magento2.analytics',
					data: {
						'name': 'Clicked for More No Results'
					}
				},
				{
					// Click on "documentation" on analytics overview page
					selector: '.algolia-analytics-overview-docs',
					name: 'magento2.analytics',
					data: {
						'name': 'Clicked Documentation Link'
					}
				},
				{
					// Click on Help & Support in main menu
					selector: 'li[data-ui-id="menu-algolia-algoliasearch-support"] a',
					name: 'magento2.help',
					data: {
						'name': 'Clicked Help & Support'
					}
				},
				{
					// Click on Contact us on Help & Support page
					selector: '.algolia-support-contact-us',
					name: 'magento2.help.contact',
					data: {
						'name': 'Clicked Contact Us'
					}
				},
				{
					// Click on Upgrade plan on Help & Support page
					selector: '.algolia-support-upgrade-plan',
					name: 'magento2.help.upgrade',
					data: {
						'name': 'Clicked Plan Upgrade'
					}
				},
				{
					// Click on Merchandising in main menu
					selector: 'li[data-ui-id="menu-algolia-algoliasearch-merchandising"] a',
					name: 'magento2.menu',
					data: {
						'name': 'Clicked Merchandising'
					}
				},
				{
					// Click on Query Merchandiser on Merchandisign page
					selector: '.algoliasearch-merchandising-options .query-merchandising a',
					name: 'magento2.merchandisign',
					data: {
						'name': 'Clicked Query Merchandiser'
					}
				},
				{
					// Click on Category Merchandiser on Merchandisign page
					selector: '.algoliasearch-merchandising-options .category-merchandising a',
					name: 'magento2.merchandisign',
					data: {
						'name': 'Clicked Category Merchandiser'
					}
				},
				{
					// Click on Landing Page Builder on Merchandisign page
					selector: '.algoliasearch-merchandising-options .landing-page-builder a',
					name: 'magento2.merchandisign',
					data: {
						'name': 'Clicked Landing Page Builder'
					}
				},
				{
					// Click on "documentation" on query merchandiser overview page
					selector: '.algolia-query-merchandiser-docs',
					name: 'magento2.querymerch.listing',
					data: {
						'name': 'Clicked Documentation Link'
					}
				},
				{
					// Click on "Merchandise a new query" on query merchandiser overview page
					selector: '.algolia-query-merchandiser-create',
					name: 'magento2.querymerch.listing',
					data: {
						'name': 'Clicked Merchandise A New Query'
					}
				},
				{
					// Click on "Merchandise a new query" on query merchandiser overview page
					selector: '.algolia-query-merchandiser-create, .algolia-algoliasearch-query-index #add',
					name: 'magento2.querymerch.listing',
					data: {
						'name': 'Clicked Merchandise A New Query'
					}
				},
				{
					// Click on "Edit" on query merchandiser overview page
					selector: '.algolia-algoliasearch-query-index a[data-action="item-edit"]',
					name: 'magento2.querymerch.listing',
					data: {
						'name': 'Clicked Edit A Query'
					}
				},
				{
					// Click on "Delete" on query merchandiser overview page
					selector: '.algolia-algoliasearch-query-index a[data-action="item-delete"]',
					name: 'magento2.querymerch.listing',
					data: {
						'name': 'Deleted Query'
					}
				},
				{
					// Click on "View" on query merchandiser overview page
					selector: '.algolia-algoliasearch-query-index a[data-action="item-view"]',
					name: 'magento2.querymerch.listing',
					data: {
						'name': 'Viewed Query on the Store'
					}
				},
				{
					// Click on "Delete" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit #delete',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Deleted Query'
					}
				},
				{
					// Click on "View" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit #view',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Viewed Query on the Store'
					}
				},
				{
					// Click on "Save & Continue" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit #save_and_continue',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Saved Query And Stayed'
					}
				},
				{
					// Click on "Save" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit #save',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Saved Query'
					}
				},
				{
					// Click on "Pin product" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit .pinIt',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Pinned Product'
					}
				},
				{
					// Click on "Unpin product" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit .unpinIt',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Unpinned Product'
					}
				},
				{
					// Click on "Arrow up" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit .arrow.up',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Promoted Product'
					}
				},
				{
					// Click on "Arrow down" on query merchandiser edit page
					selector: '.algolia-algoliasearch-query-edit .arrow.down',
					name: 'magento2.querymerch.edit',
					data: {
						'name': 'Demoted Product'
					}
				},
				{
					// Click on "Create New Landing Page" on landing page builder overview page
					selector: 'algolia-landing-page-builder-create, .algolia-algoliasearch-landingpage-index #add',
					name: 'magento2.landing.listing',
					data: {
						'name': 'Clicked Create New Landing Page'
					}
				},
				{
					// Click on "Edit" on landing page builder overview page
					selector: '.algolia-algoliasearch-landingpage-index a[data-action="item-edit"]',
					name: 'magento2.landing.listing',
					data: {
						'name': 'Clicked Edit Page'
					}
				},
				{
					// Click on "Delete" on landing page builder overview page
					selector: '.algolia-algoliasearch-landingpage-index a[data-action="item-delete"]',
					name: 'magento2.landing.listing',
					data: {
						'name': 'Clicked Delete Page'
					}
				},
				{
					// Click on "View" on landing page builder overview page
					selector: '.algolia-algoliasearch-landingpage-index a[data-action="item-view"]',
					name: 'magento2.landing.listing',
					data: {
						'name': 'Viewed a page on the store'
					}
				},
				{
					// Click on "Duplicate" on landing page builder overview page
					selector: '.algolia-algoliasearch-landingpage-index a[data-action="item-duplicate"]',
					name: 'magento2.landing.listing',
					data: {
						'name': 'Duplicated a page'
					}
				},
				{
					// Click on "Delete" on landing page builder edit page
					selector: '.algolia-algoliasearch-landingpage-edit #delete',
					name: 'magento2.landing.edit',
					data: {
						'name': 'Deleted Page'
					}
				},
				{
					// Click on "View" on landing page builder edit page
					selector: '.algolia-algoliasearch-landingpage-edit #view',
					name: 'magento2.landing.edit',
					data: {
						'name': 'Viewed a page on the store'
					}
				},
				{
					// Click on "Duplicate" on landing page builder edit page
					selector: '.algolia-algoliasearch-landingpage-edit #duplicate',
					name: 'magento2.landing.edit',
					data: {
						'name': 'Duplicated a page'
					}
				},
				{
					// Click on "Save" on landing page builder edit page
					selector: '.algolia-algoliasearch-landingpage-edit #save',
					name: 'magento2.landing.edit',
					data: {
						'name': 'Saved page'
					}
				},
				{
					// Click on "Save & Continue" on landing page builder edit page
					selector: '.algolia-algoliasearch-landingpage-edit #save_and_continue',
					name: 'magento2.landing.edit',
					data: {
						'name': 'Saved page and stayed'
					}
				}
            ];

            eventsToTrack.forEach(function(event) {
                $(event.selector).click(function() {
                    trackEvent(event.name, event.data);
                });
            });
		});
	});

	requirejs([
		'jquery',
		'Magento_Ui/js/lib/validation/validator',
		'mage/translate',
        'prototype'
	], function ($, validator, mage) {
		'use strict';

      $(".close-box").click(function() {
        $(this).parent().hide();
      });

      validator.addRule(
        'validate-query-usage',
        function (value) {
          var isValid = true;
          var storeId = $('select[name="store_id"]').val();
          var queryId = $('input[name="query_id"]').val();

          var url = ajaxCheckQuery;

          // Only check if the focus is not on the search
          if ($(':focus').attr('name') != 'query_text') {
              new Ajax.Request(
                url,
                {
                    parameters: {'store_id': storeId, 'query_text': value, 'query_id': queryId},
                    method: 'post',
                    asynchronous: false,
                    onComplete: function (transport) {
                    var response = JSON.parse(transport.responseText);
                    isValid = response.isValid;
                }
              }
            );
          }

          return isValid;
        },
        $.mage.__('This query is already connected to another query rule. Please enter a different query or edit the existing one.')
      );

      validator.addRule(
        'validate-algolia-index',
        function (value) {

          if (typeof window.algoliaSearchConfig.indexDataByStoreIds[value]== "undefined") {
            return false;
          }

          return true;
        },
        $.mage.__('The index corresponding to the store you selected doesn\'t exist.')
      );

        validator.addRule(
            'validate-url-unicity',
            function (value) {
                var isValid = false;
                var storeId = $('select[name="store_id"]').val();
                var landingPageId = $('input[name="landing_page_id"]').val();
                var url = ajaxCheckUrl;

                new Ajax.Request(
                    url,
                    {
                        parameters: {'store_id': storeId, 'url_key': value, 'landing_page_id': landingPageId},
                        method: 'post',
                        asynchronous: false,
                        onComplete: function (transport) {
                            var response = JSON.parse(transport.responseText);
                            isValid = response.isValid;
                        }
                    }
                );
                return isValid;
            },
            $.mage.__('This URL key is already in use. Please find another one.')
        );
	});
});
</script>
